server/delta/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin
from delta import views as vie
from delta.resources import statusResource,ledResource
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
status_resource = statusResource()
led_resource=ledResource()
app_name = 'delta'
urlpatterns = [
    path('admin/', admin.site.urls),
    #path('accounts/', include('django.contrib.auth.urls')),
    #accounts/login/ [name='login']
    #accounts/logout/ [name='logout']
    #accounts/password_change/ [name='password_change']
    #accounts/password_change/done/ [name='password_change_done']
    #accounts/password_reset/ [name='password_reset']
    #accounts/password_reset/done/ [name='password_reset_done']
    #accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
    #accounts/reset/done/ [name='password_reset_complete']

    url(r'^delta/', include(status_resource.urls)),
    url(r'^delta/', include(led_resource.urls)),
    path('function/',vie.function, name="function"),
    path('delta/tele/led/',vie.show , name="show"),
    path('node/led/',vie.node , name="node"),
    path('',vie.homepage),
    path('on/',vie.on, name="on"),
    path('off/',vie.off, name="off")
]
urlpatterns += staticfiles_urlpatterns()

#mydata = json.loads(request.body.decode("utf-8"))

server/server/urls.py
from django.contrib import admin
from django.urls import path , include
from main.views import login_view, register_view, logout_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('delta.urls')),
    path('accounts/login/', login_view , name="login"),
    path('accounts/register/', register_view , name="register"),
    path('accounts/logout/', logout_view , name="logout"),
]

server/delta/models.py
from django.db import models
from django.urls import reverse
class status(models.Model):
    title=models.CharField(max_length=300)
    moisture=models.IntegerField(blank=True , null=True)
    def __str__(self):
        return '%s %s' % (self.title, self.moisture)
class led(models.Model) :
    order=models.CharField(max_length=50)
    position=models.CharField(max_length=50)
    #slug=models.SlugField(max_length=50)
    def __str__(self):
        return '%s %s' % (self.order, self.position)
    def get_absolute_url(self):
        return reverse('show', kwargs={"id": self.id})

server/main/models.py
from django.db import models

server/main/forms.py
from django import forms
from django.contrib.auth import (
    authenticate,
    get_user_model

)

User = get_user_model()


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError('This user does not exist')
            if not user.check_password(password):
                raise forms.ValidationError('Incorrect password')
            if not user.is_active:
                raise forms.ValidationError('This user is not active')
        return super(UserLoginForm, self).clean(*args, **kwargs)

Locations_choices = [
    ('Hamedan', 'Hamedan'),
    ('Tehran', 'Tehran'),
    ('Shiraz', 'Shiraz'),
]
class UserRegisterForm(forms.ModelForm):
    firstname=forms.CharField(max_length=None)
    lastname=forms.CharField(max_length=None)
    location = forms.ChoiceField(widget=forms.RadioSelect,
    choices=Locations_choices
    )
    email = forms.EmailField(label='Email address')
    email2 = forms.EmailField(label='Confirm Email')
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            'firstname',
            'lastname',
            'username',
            'email',
            'email2',
            'password',
            'location',
        ]

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get('email')
        email2 = self.cleaned_data.get('email2')
        if email != email2:
            raise forms.ValidationError("Emails must match")
        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError(
                "This email has already been registered")
        return super(UserRegisterForm, self).clean(*args, **kwargs)

server/delta/views.py
import django
from django.shortcuts import render,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
import json
from django.http import JsonResponse
from delta.models import status,led
from django.db import connection
from django.views.decorators.csrf import csrf_protect
def node(request):
    response={'moisture':678
    }
    return JsonResponse(response)
    #queryset = led.objects.all()
def show(request):
    ##form=nodemcu(request.POST or None)
    obj=get_object_or_404(status, id=5)
    ##if form.is_valid():
    ##    form.save()
    #obj= status.objects.get(id=5)
    ##x=len(request.POST)
    mydata=json.loads(request.body.decode('utf-8'))
    ##obj.moisture=json.loads(receiveddata)
    obj.moisture=mydata["moisture"]
    obj.title=mydata["state"]
    obj.save()
    obj2=get_object_or_404(led,id=1)
    ##m=json.loads(f)
    #id_ = self.kwargs.get("id")
    if request.method =='POST':
        response={
        'method':request.method,
        'moisture':obj.moisture,
        'state':obj2.order
        }
        return JsonResponse(response)
    elif request.method =='GET':
        response={
        'method':request.method,
        'moisture':m["moisture"],
        'state':obj2.order
        }
        return JsonResponse(response)

##    response={
##    'abas':f,
##    'state':'on',
##    }
    ##return JsonResponse(response)
    ##if request.headers['connection'] =='close':
        ##connection.close()
@login_required
def function(request):
    obj= status.objects.get(id=5)
    obj2= led.objects.get(id=1)
    content={
    'title': obj.title ,
    'state': obj.moisture,
    'position': obj2.position
    }
    return render(request,'delta/show.html',content)
@login_required
def off(request):
    obj= led.objects.get(id=1)
    obj.order='off'
    obj.position='off'
    obj2= status.objects.get(id=5)
    #obj.slug='on to off'
    obj.save( )
#    post=led.objects.create(order='off',position='off')
#    post.save()
    content={
    'order': obj.order ,
    'position': obj.position,
    'title': obj2.title ,
    'state': obj2.moisture
    }
    return render(request,'delta/show.html',content)
@login_required
def on(request):
    obj= led.objects.get(id=1)
    obj.order='on'
    obj.position='on'
    obj2= status.objects.get(id=5)
    #obj.slug='off to on'
    obj.save()
    content={
    'order': obj.order ,
    'position': obj.position,
    'title': obj2.title ,
    'state': obj2.moisture
    }
    return render(request,'delta/show.html',content)
def homepage(request):
#    person= {'firstname': 'farzin', 'lastname': 'Daniels'}
#    weather= "sunny"
#    context= {
#        'person': person,
#        'weather': weather,
#        }

    return render(request,'delta/base.html')

server/main/views.py
from django.shortcuts import render, redirect

from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout
)
from .forms import UserLoginForm, UserRegisterForm
def login_view(request):
    next = request.GET.get('next')
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)
        if next:
            return redirect(next)
        return redirect('/')

    context = {
        'form': form,
    }
    return render(request, "main/login.html", context)


def register_view(request):
    next = request.GET.get('next')
    form = UserRegisterForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        password = form.cleaned_data.get('password')
        user.set_password(password)
        user.save()
        new_user = authenticate(username=user.username, password=password)
        login(request, new_user)
        if next:
            return redirect(next)
        return redirect('/')

    context = {
        'form': form,
    }
    return render(request, "main/signup.html", context)

def logout_view(request):
    logout(request)
    return redirect('/')

server/templates/base.html
<!DOCTYPE html>
{% load static from staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>THE FLOW</title>
    <style>html{font-family: Helvetica; display:inline-block; margin: 0px auto; text-align: center;}
  h1{color: #0F3376; padding: 2vh;}p{font-size: 1.5rem;}.button{display: inline-block; background-color: #e7bd3b; border: none;
  border-radius: 4px; color: white; padding: 16px 40px; text-decoration: none; font-size: 30px; margin: 2px; cursor: pointer;}
  .button2{background-color: #4286f4;}.button3{background-color: #a61263;}</style>
  </head>
  <body>

    <h1>welcome!!!</h1>
    {%block content %}

    {%endblock content%}
    <p>GPIO state: {{position}} </p>
    <p><a href="{%url 'off'%}"><button class="button">OFF</button></a></p>
    <p><a href="{%url 'on'%}"><button class="button button2">ON</button></a></p>
    <p><a href="{%url 'function'%}"><button class="button button3">soil moisture</button></a></p>
    <p> iot api </p>
    <form action="http://google.com">
    <input type="submit" value="Go to Google" />
    </form>
  </body>
</html>

server/templates/delta/base.html
<!DOCTYPE html>
{% load static from staticfiles %}
<html lang="en" dir="ltr">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <head>
    <meta charset="utf-8">
    <title>THE FLOW</title>
    <style>html{font-family: Helvetica; display:inline-block; margin: 0px auto; text-align: center;}
  h1{color: #0F3376; padding: 2vh;}p{font-size: 1.5rem;}.button{display: inline-block;background-color: #E82B25; border: none;
  border-radius: 4px; color: white; padding: 16px 40px; text-decoration: none; font-size: 30px; margin: 2px; cursor: pointer;}
  .button2{background-color: #e7bd3b;}.button3 {background-color: #a61263;}.italic {font-style: italic;}
</style>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
    <h1>WELCOME TO FLOW!!!</h1>
    <p class="italic"> IOT PROFESSIONAL API </p>
    <li><a href="{% url 'login'%}"> login</a></LI>
    <li><a href="{% url 'logout'%}"> logout</a></LI>
    <li><a href="{% url 'register'%}"> register</a></LI>
    {% if user.is_authenticated %}
      <p class="italic">Hi {{ user.username }} what's up?!</p>
    {% else %}
      <p class="italic">You are not logged in for enabling change and manage your stracture please login first</p>
    {% endif %}
  </ul>
        </div>
      </nav>
    {%block content %}

    {%endblock content%}
    {% if user.is_authenticated %}
    <p>GPIO state: {{position}} </p>
    <p class="italic"><a href="{%url 'delta:on'%}"><button onclick="alert('You turned off flowerpot')" class="button button2">ON</button></a></p>
    <p class="italic"><a href="{%url 'delta:off'%}"><button onclick="alert('You turned on flowerpot')" class="button">OFF</button></a></p>
    <p class="italic"><a href="{%url 'delta:function'%}"><button class="button button3">soil moisture</button></a></P>
    <a><select id="groups" name="groups">
      <optgroup label="state">
        <option>damp</option>
        <option selected>waterlogged</option>
        <option>dranch</option>
        <option>dry</option>
        </optgroup>
    </select></a>
    <input type="submit" value="submit">

    {% endif %}
  </body>
</html>

server/templates/delta/show.html
{% extends 'delta/base.html'%}

{%block content%}

<p>{{title}}</p>
<p>{{state}}</p>
<p>{{inputdata}}</p>

{%endblock content%}

server/templates/main/homepage.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <h1>This is the home page</h1>
</body>

</html>

server/templates/main/login.html
{% extends 'delta/base.html'%}

{%block content%}
<div class="container">
  <div class="jumbotron">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" />
    </form>
  </div>
</div>
{%endblock content%}

server/templates/main/signup.html
{% extends 'delta/base.html'%}

{%block content%}
<div class="container">
  <div class="jumbotron">
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" />
    </form>
  </div>
</div>
{%endblock content%}

server/templates/show.html
{% extends 'base.html'%}

{%block content%}
<p>{{title}}</p>
<p>{{state}}</p>
<p>{{inputdata}}</p>

{%endblock content%}